# Generated by Django 3.2.23 on 2024-01-11 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheDailyBugle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='postarticle',
            name='category_image',
            field=models.ImageField(upload_to='articles/'),
        ),
    ]
