# Generated by Django 3.2.23 on 2024-01-13 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheDailyBugle', '0003_auto_20240111_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='postarticle',
            name='article_body',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
