# Generated by Django 3.2.23 on 2024-01-15 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheDailyBugle', '0007_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='profile_image',
            field=models.ImageField(null=True, upload_to='profilepic/'),
        ),
    ]
